### ISSUE TITLE
realsense test problem

### ISSUE THREAD

**Issue by kiwiwan** [graspnet/anygrasp_sdk#13]
I have 3 problem in my testing for anygrasp_sdk using a realsense d435i. I hope you can help me with these questions. Thanks!
1. Points form realsense d435i are seem poor. For example:
![image](https://github.com/graspnet/anygrasp_sdk/assets/16831845/ca2eb7ad-578e-4415-8fa7-409aede950f3)
![image](https://github.com/graspnet/anygrasp_sdk/assets/16831845/3d4a714a-d582-4a92-9e5f-8b60a9db116d)
Have you done some calibrate for your realsense?
2. After the depth image is aligned to the RGB image, more grasp can be obtained by using the intrinsics parameters of the original depth camera to calculate the point cloud than by using the intrinsics parameters of the RGB camera, especially when no grasp can be detected by using the intrinsics parameters of the RGB camera. Why does this phenomenon happen?
3. I found that using 1280x720 images had a better chance of detecting grasp than using 640x480 images. Is this a normal phenomenon?

**Comment by Fang-Haoshu** [comment]
Hi, please try some other objects that have no transparency. The bottle shown in the figure is a bit transparent and the depth is usually bad in this case. We do not calibrate the realsense.

2. We have no idea about that. But you should use the intrinsics of the RGB camera after you align the depth, otherwise there will be some offsets for the pointcloud, resulting in offsets in the detected grasp poses.

3. Yes, 1280x720 means there are more points in the point cloud. We also use 1280x720.
